name: Rust

on:
  push:
    branches: [ master ]

jobs:
  clippy:
    runs-on: ubuntu-latest
    name: Clippy Check
    steps:
    - uses: actions/checkout@v2
    - name: Install Nightly Rust with Clippy
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: clippy
        override: true
    - name: Annotate commit with Clippy warnings
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
        name: Clippy Check
